# Site settings
author: Nick Levenson
title: Nick's Blog
header-img: img/home-bg.png
email: nicklevenson@gmail.com
copyright_name: Nick Levenson
description: > # this means to ignore newlines until "baseurl:"
  A place to hear Nick's thoughts
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nicklevenson

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
